#! /bin/sh
#reference: coursera lecture slides

case "$1" in
    start)	
    echo "Starting linux driver"
        start-stop-daemon -S -n scull_load -a /usr/bin/scull_load
        start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
        modprobe -v hello
        ;;
    stop)
    echo "Stopping linux driver" 
    #start-stop-daemon -K -n scull
    start-stop-daemon -S -n scull_unload -a /usr/bin/scull_unload
    start-stop-daemon -S -n module_unload -a /usr/bin/module_unload -- faulty
    #start-stop-daemon -K -n module
    rmmod -v hello
    ;;
    *)
         echo "Usage: $0 {start|stop}" 
        exit 1 
esac

exit 0